# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

AWSTemplateFormatVersion: '2010-09-09'
Description: 'Template for StacKSet to create cross account role accessible by Network VPC account'

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Required Parameters
        Parameters:
            - networkAccountId
    ParameterLabels:
      networkAccountId:
        default: AWS Account ID for Network Services

Parameters:
  networkAccountId:
    Type: String
    Description: Account ID of the shared network resources

Conditions:
  IsNetworkAccount: !Equals [!Ref networkAccountId, !Ref AWS::AccountId] 
  NotNetworkAccount: !Not [!Equals [!Ref networkAccountId, !Ref AWS::AccountId]]

Resources:
## ToDo set to only deploy once when deploying multi region
  NetworkParameterExecutionRole:
    Type: AWS::IAM::Role
    Condition: NotNetworkAccount
    Properties:
      RoleName: NetworkParameterExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${networkAccountId}:root'
            Action: sts:AssumeRole
            Condition:
              StringLike:
                aws:PrincipalArn: '*NetworkParameterAdminRole'
      Policies:
        - PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:*
                  - s3:*
                  - sns:*
                Resource: '*'
              - Effect: Allow
                Action:
                  - ssm:PutParameter
                  - ssm:DeleteParameter
                  - ssm:AddTagsToResource
                Resource: '*'
          PolicyName: NetworkParameterExecutionPolicy
  
  # IAM Role for Lambda function that creates parameter store items across accounts
  NetworkParameterAdminRole:
    Type: 'AWS::IAM::Role'
    Condition: IsNetworkAccount
    Properties:
      RoleName: NetworkParameterAdminRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: shareVpcParameters
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: sts:AssumeRole
                Resource: arn:aws:iam::*:role/NetworkParameterExecutionRole

